### ISSUE TITLE
Update add-on `script.tv.show.next.aired`

### ISSUE THREAD

**Issue by detobel36** [luizoti/skin.xperience1080#3]
Log message:
```
ERROR <general>: Add-on 'script.tv.show.next.aired' is not compatible with Kodi
```

Two update exist:
- https://github.com/scott967/script.tv.show.next.aired/tree/Matrix_py3
- https://github.com/kodi-community-addons/script.tv.show.next.aired

Don't know which one is better...

**Comment by luizoti** [comment]
So I did some tests, I may be mistaken, but these add-ons are not yet available, apart from that there are many add-ons that need to be installed, so much that I can't run here, I will try to do some tests and detect problems in the matrix version, but I can't guarantee that I will now study a way to adapt the code, not least because I haven't started using the kodi 19 yet.

If you are willing to test, I can put you as a contributor, I believe it is enough to be able to do tests and merge pull requests if they exist.

**Comment by detobel36** [comment]
I didn't follow you...     
Yes the link that I give you are linked to "in dev" sources.  But this already allow to test the skin.    

I didn't catch why you say that "many add-ons needs to be installed". Only 3, linked here: https://github.com/luizoti/skin.xperience1080/pull/5

For the install, just download the zip file from github and install it on kodi (using "install from zip").

**Comment by luizoti** [comment]
I cloned the repositories, maybe that was the problem, with that he asked for the installation of the dependencies of these addons that you listed, I will try again later and I will install via zip to see if he can search the dependencies.
