### ISSUE TITLE
Update add-on `script.videolanguage`

### ISSUE THREAD

**Issue by detobel36** [luizoti/skin.xperience1080#4]
Error log:
```
ERROR <general>: Add-on 'script.videolanguage' is not compatible with Kodi
```

Update seems to have begin: https://github.com/krupama/script.videolanguage/pull/1
Don't know if it's finish and what is missing...

**Comment by kutmasterk** [comment]
Since a few versions of Kodi, there is no need for this plugin anymore because this function is now integrated in the skinning engine.

You can check my commits to make this work:
https://github.com/krupama/skin.xperience1080/commit/eff868e16d48b2d99fc21140181ff3611c12d57d
https://github.com/krupama/skin.xperience1080/commit/cc8d5a09948440d09c941fcc59b05590fb88622a

**Comment by detobel36** [comment]
Thx
@krupama You have updated the theme but you change it a bit no ?

**Comment by kutmasterk** [comment]
Yes. I did update the theme to a more modern look. removed the hooks for extendedinfo.skript and replaced it with the new "TheMovieDB Helper", removed TVShowNextAired and script.videolanguage completly from the skin. Also made the REBOOT, SHUTDOWN, SLEEP Buttons in the Menu work again and put a Youtube Trailer Search on every Movie- and TVShow-Infopage.

The Skin now pretty much works flawless in Kodi 19.
